name: getx_hacker_news_api
description: NewsAPI app with GetX.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # api
  retrofit: any
  logger: any  
  # network info
  connectivity: ^0.4.9+3
  # functional programming
  dartz: ^0.9.2
  # value equality  
  equatable: ^1.2.5
  # json
  json_annotation: ^3.1.0
  # freezed
  freezed_annotation: ^0.12.0
  # meta
  meta: ^1.2.3
  # bloc state managment
  flutter_bloc: ^6.0.6
  # GetX mico-framework
  get: ^3.24.0
  # network
  http: ^0.12.2
  # date formatter
  intl: ^0.16.1
  # improve code
  lint: ^1.3.0
  # device native folders 
  path_provider: ^1.6.18
  # sql db (local storage)
  sqflite: ^1.3.1+1
  # no sql db (local storage)
  sembast: ^2.4.7+7
  # no sql db (local storage)
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # url helper
  url_launcher: ^5.7.2
  # IoC
  kiwi: ^2.1.1


dev_dependencies:
  # tests
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito:
  bloc_test: ^7.1.0
  test: any  

  # native icons & splash
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9

  # code generators
  build_runner: ^1.10.3
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  retrofit_generator: any
  hive_generator: ^0.8.1
  kiwi_generator: ^2.1.1

# flutter icons setup
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

# flutter splash screen setup
flutter_native_splash:
  image: assets/images/splash_icon.png
  color: "#FFEB3B"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/loading.jpg
    - assets/images/placeHolder.jpg
